import type { Metadata } from "next";
import { Inter, Oswald } from "next/font/google";

import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";
import Background from "@/components/Background";

const inter = Inter({ subsets: ["latin"] });

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
});

export const metadata: Metadata = {
  title: "Trust Social",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} ${oswald.variable} antialiased min-h-screen flex`}
      >
        <SessionProvider>
          <Background>{children}</Background>
          <Toaster richColors />
        </SessionProvider>
      </body>
    </html>
  );
}
